### ISSUE TITLE
[Feature Request] adding @updateURL

### ISSUE THREAD

**Issue by black-backdoor** [Hakorr/CommLink#1]
as far as i know imported scripts - @require are just the same as other userscripts so it should be possible to add @updateURL to your CommLink.js file for automated updates

[https://stackoverflow.com/questions/72545851/how-to-make-userscript-auto-update-from-private-domain-github](https://stackoverflow.com/questions/72545851/how-to-make-userscript-auto-update-from-private-domain-github)

**Comment by Hakorr** [comment]
https://github.com/AugmentedWeb/UserGUI/issues/7#issuecomment-1755434101

**Comment by black-backdoor** [comment]
as far as i know it's still possible for libarys to have a script header

**Comment by black-backdoor** [comment]
in Tampermonkey there is a Setting called externals with the parameter update interval

[this ](https://greasyfork.org/scripts/372672-everything-hook/code/Everything-Hook.js)for example is a libary but it still has a userscript header

**Comment by black-backdoor** [comment]
I haven't found anything about this topic on the internet, so I thought just post it. As far as I understand, Tampermonkey just redownloads the @require script every day.

**Comment by black-backdoor** [comment]
I just thought it would be nice if it updates regularly because I plan to use this amazing Script in future projects.

**Comment by Hakorr** [comment]
> I just thought it would be nice if it updates regularly because I plan to use this amazing Script in future projects.

You shouldn't require it directly from GitHub anyway. I'm still planning on updating the library and might make big changes, which would then break your userscript. Just require the library via GreasyFork,
```js
// @grant       GM_getValue
// @grant       GM_setValue
// @grant       GM_deleteValue
// @grant       GM_listValues
// @require     https://greasyfork.org/scripts/470418-commlink-js/code/CommLinkjs.js?version=1217207
```

You cannot use "@updateURL" to require libraries.

**Comment by Hakorr** [comment]
> I haven't found anything about this topic on the internet

[This is a great source](https://www.tampermonkey.net/documentation.php?locale=en) (Tampermonkey docs)

Userscript managers should automatically check the URL that was used to install the userscript for updates. I think the "@updateURL" is just if you want it to update from a specific URL regardless of what URL it was installed from.

**Comment by Hakorr** [comment]
> as far as i know it's still possible for libarys to have a script header

Oh, okay, I didn't know about this. I doubt it's possible, but maybe you're right?

**Comment by black-backdoor** [comment]
I tested it, it doesn't make a difference. In the settings in Tampermonkey you can set how long the external files should be stored until they get reloaded.

But as far I found out it script headers also work in libraries.

**Comment by Hakorr** [comment]
> But as far I found out it script headers also work in libraries.

Test granting the library something, and then seeing if it works without the userscript having that grant.

**Comment by black-backdoor** [comment]
> > But as far I found out it script headers also work in libraries.
> 
> Test granting the library something, and then seeing if it works without the userscript having that grant.

Nope, does not work. (on Violentmonkey and Tampermonkey)

I think we can say it useless and not possible to have a header in libraries. In the documentation of Tampermonkey, there is nothing about updating libraries.


The Tampermonkey docs is very unspecific in this situation. 


> @require
> 
> Points to a JavaScript file that is loaded and executed before the script itself starts running. Note: the scripts loaded via @require and their "use strict" statements might influence the userscript's strict mode!
